model:
  n_layers: 5  #Transformer-blokker (var 4)
  n_heads: 4  #attention heads i hver transformer layer
  d_model: 256   #dimensjonen på embeddding aka n_embd (var 128)
  context_length: 256   #hvor mange tokens modellen ser samtidig, aka block_size (var 128)
  ff_mult: 4 #Hvor mye vi utvider embedding-dimensjonen i feed-forward-laget
  dropout: 0.1 #Dropout i modellen. Satt til 0.0 for nå aka ingen effekt før vi begynner å tweake.

training:
  batch_size: 24  #hvor mange sekvenser pr treningsstep (var 32)
  lr: 3e-4  #learning rate (var 3e-4)
  max_iters: 30000  #hvor mange treningsteps. SKal stå 15000 her
  eval_interval: 100  # Hvor ofte vi evaluerer og logger. Skal stå 100 her
  eval_iters: 20  # Hvor mange batches vi bruker når vi estimerer loss
  train_split: 0.9  # Hvor stor del av data som brukes til trening
  device: "cuda"  # Bruk GPU hvis tilgjengelig.
  weight_decay: 0.00 # Weight decay for regularisering i AdamW
  grad_clip: 0.0 # Klipper gradientnormen for å unngå eksploderende gradients, (feks 1.0)
  early_stopping: true  # Stopper trening hvis val-loss ikke forbedres
  patience: 20  # Hvor mange eval-runder vi tåler uten forbedring, aka hvor lenge skal vi vente. (var 10)
  min_delta: 0.0005  # Minste forbedring i val-loss som teller som ekte forbedring, aka hva er "forbedring". (var 0.001)
  train_ratio: 0.8 # Andel av data som brukes til trening
  val_ratio: 0.1 # Andel av data som brukes til validering (resten brukes til test)

logging:
  use_wandb: true  # Logge til Weights & Biases
  entity: "671469-h-gskulen-p-vestlandet"  # W&B entity/team
  project: "Test-Linn"
  #project: "mini-shakespeare-gpt"  # Prosjektnavn i W&B
  run_name: "baseline"  # Navn på denne run-en

checkpoint:
  out_dir: "models"  # Mappe der modellen lagres
  save_path: "models/shakespeare_model.pt"  # Filsti til lagret modell

generation:
  prompt: "ROMEO:" # starttekst for generering, (var "Thou art")
  max_new_tokens: 1000  # hvor mange nye tokens som skal genereres (var 200)
  temperature: 0.8  # styrer hvor tilfeldig output er. (var 0.7)
  do_sample: true  # om vi sampler eller velger mest sannsynlige token
  top_k: 40  # sample kun fra de k mest sannsynlige tokenene. (var 20)
  # top_p: null  # nucleus sampling, Sett til null hvis ubrukt. Tenker å evt prøve å legge den inn senere, siden den er mer vanlig for GPT modeller

tokenizer:
  type: "bpe"  # "char" eller "bpe"
  vocab_size: 1024  # størrelse på BPE-vokabular (var 512)
  min_frequency: 2  # minste frekvens for BPE-token
  model_path: models/bpe_tokenizer_train_only.json # hvor tokenizer lagres / lastes fra